routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\frontend\FrontendController;
use App\Http\Controllers\admin\ProductCategoryController;
use App\Http\Controllers\admin\ProductAttributeController;
use App\Http\Controllers\admin\ProductController;
use App\Http\Controllers\admin\OfferController;
use App\Http\Controllers\admin\SliderController;
use App\Http\Controllers\frontend\CartController;
use App\Http\Controllers\frontend\CheckoutController;
use App\Http\Controllers\admin\OrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [FrontendController::class, 'index'])->name('home_route');
Route::get('/shop', [FrontendController::class, 'shop'])->name('shop_route');
Route::get('/product-details/{id}', [FrontendController::class, 'productDetails'])->name('product_details_route');
Route::get('/category-product/{id}', [FrontendController::class, 'categoryProduct'])->name('category_product_route');
Route::get('/search', [FrontendController::class, 'searchProduct'])->name('search_product_route');

Route::resource('cart',CartController::class);
Route::get('checkout',[CheckoutController::class,'index'])->name('checkout_route');
Route::post('place-order',[CheckoutController::class,'placeOrder'])->name('place_order_route');


//admin route
Route::prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth'], function(){
        Route::get('dashboard',[AdminController::class, 'index'])->name('admin.dashboard');
        Route::resource('category',ProductCategoryController::class);
        Route::resource('attribute',ProductAttributeController::class);
        Route::resource('product',ProductController::class);
        Route::resource('offer',OfferController::class);
        Route::resource('slider',SliderController::class);
        Route::resource('order',OrderController::class);
    });
});

app/Http/Controllers/frontend/CartController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Cart;
use App\Models\Product;
use Illuminate\Support\Facades\Session;


class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = cartItem();
        return view('frontend.cart',compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

         $product = Product::find($request->product_id);

         $product_id = $request->product_id;

         $attribute_id = $request->attribute_id;

        if($product_id &&  $attribute_id){

            $old_data = Cart::where(['product_id'=>$product_id,'attribute_id'=>$attribute_id,'customer_id'=>Session::getId()])->first();

            if($old_data){
                $total_qty   = $request->quantity+$old_data->quantity;
                $total_price = $product->product_price*$total_qty;
                $data = [
                    'product_id'=>$product_id,
                    'attribute_id'=>$attribute_id,
                    'customer_id'=>Session::getId(),
                    'quantity'=>$request->quantity+$old_data->quantity,
                    'total_price'=>$total_price,
                ];
                Cart::where(['product_id'=>$product_id,
                'attribute_id'=>$attribute_id,
                'customer_id'=>Session::getId()])->update($data);
            }
            else{
                $total_qty = $request->quantity;
                $total_price = $product->product_price*$total_qty;
                $data = [
                    'product_id'=>$product_id,
                    'attribute_id'=>$attribute_id,
                    'customer_id'=>Session::getId(),
                    'quantity'=>$request->quantity,
                    'total_price'=>$total_price,
                ];
                Cart::insert($data);
            }

        }
        elseif($product_id &&  $attribute_id==null){
            $old_data = Cart::where(['product_id'=>$product_id,'customer_id'=>Session::getId()])->first();
            if($old_data){
                $total_qty   = $request->quantity+$old_data->quantity;
                $total_price = $product->product_price*$total_qty;
                $data = [
                    'product_id'=>$product_id,
                    'attribute_id'=>$attribute_id,
                    'customer_id'=>Session::getId(),
                    'quantity'=>$total_qty,
                    'total_price'=>$total_price,
                ];
                Cart::where(['product_id'=>$product_id,
                'customer_id'=>Session::getId()])->update($data);
            }
            else{
                $total_qty = $request->quantity;
                $total_price = $product->product_price*$total_qty;
                $data = [
                    'product_id'=>$product_id,
                    'attribute_id'=>$attribute_id,
                    'customer_id'=>Session::getId(),
                    'quantity'=>$total_qty,
                    'total_price'=>$total_price,
                ];
                Cart::insert($data);
            }
        }

       return response()->json(['success','প্রোডাক্ট আপনার ব্যাগে যুক্ত করা হয়েছে']);

    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        if($request->quantity==0){
            Cart::find($id)->delete();
            return redirect()->route('cart.index')->with('success','আইটেম আপডেট করা হয়েছে');
        }

        $cart = Cart::find($id);

        $product = Product::find($cart->product_id);

        $total_price = $product->product_price*$request->quantity;

        $data = [
            'quantity'=>$request->quantity,
            'total_price'=>$total_price,
        ];

        Cart::where('id',$id)->update($data);

        return redirect()->route('cart.index')->with('success','আইটেম আপডেট করা হয়েছে');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cart = Cart::find($id);

        $cart->delete();
        return redirect()->route('cart.index')->with('error','আইটেম সরানো হয়েছে');
    }
}

app/Http/Controllers/frontend/CheckoutController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Order;
use App\Models\OrderItem;
use Illuminate\Support\Facades\Session;
use Facebook\Facebook;
use Facebook\Exceptions\FacebookResponseException;
use Facebook\Exceptions\FacebookSDKException;

class CheckoutController extends Controller
{
    public function index(){
        $data = cartItem();
        return view('frontend.checkout',compact('data'));
    }

    function sendFacebookPageMessage($pageAccessToken, $pageId, $message) {
        $fb = new Facebook([
            'app_id' => 'your_app_id',
            'app_secret' => 'your_app_secret',
            'default_graph_version' => 'v13.0', // Update to the latest version
        ]);

        try {
            // Send a message to your page owner
            $response = $fb->post("/$pageId/messages", [
                'message' => $message,
            ], $pageAccessToken);

            $graphNode = $response->getGraphNode();
            // Handle success

        } catch (FacebookResponseException $e) {
            // Handle error

        } catch (FacebookSDKException $e) {
            // Handle error
        }
    }

    public function placeOrder(Request $request){

        $data = cartItem();

        $order = new Order;
        $order->customer_id = Session::getId();
        $order->name = $request->name;
        $order->email = $request->email;
        $order->mobile = $request->mobile;
        $order->address = $request->address;
        $order->delivery_charge = str_replace("Tk ", "", deliveryCharge());
        $order->save();

        $invoice = $order->id.rand();

        Order::where('id',$order->id)->update(['invoice_no'=>$invoice]);

        foreach($data as $item){
            $order_item = new OrderItem;
            $order_item->order_id = $order->id;
            $order_item->product_id = $item->product_id;
            $order_item->attribute_id = $item->attribute_id;
            $order_item->quantity = $item->quantity;
            $order_item->total_price = $item->total_price;
            $order_item->save();
        }

        $this->sendFacebookPageMessage();

        cartDelete();

        return redirect()->route('checkout_route')->with('success', "ধন্যবাদ অর্ডার টি সফলভাবে সম্পন্ন হয়েছে.\nআপনার অর্ডার নাম্বার " .  $invoice . "।\nএই অর্ডার নাম্বার দিয়ে আপনি ট্র্যাক করতে পারবেন");


    }
}

app/Http/Controllers/frontend/FrontendController.php
<?php

namespace App\Http\Controllers\frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\ProductAttribute;
use App\Models\Slider;
use App\Models\Offer;

class FrontendController extends Controller
{
    //home page
    public function index(){
        $data['category'] = ProductCategory::where('status',1)->orderBy('id','DESC')->get();
        $data['product']  = Product::where('status',1)->orderBy('id','DESC')->get();
        $data['slider']  = Slider::where('status',1)->get();
        $data['offer']  = Offer::where('status',1)->get();
        return view('frontend.index',compact('data'));
    }

     //shop page
     public function shop(Request $request){
        if($request->attribute_id){
            $data['product']  = Product::where('status',1)
            ->join('product_attributes','product_attributes.product_id','=','products.id')
            ->where('att_type_id',$request->attribute_id)
            ->simplePaginate(10);
        }else{
            $data['product']  = Product::where('status',1)->simplePaginate(10);
        }

        $data['size']     = allSize();
        return view('frontend.shop',compact('data'));
    }

    public function productDetails($id){

        $data['product'] = Product::where(['id'=>$id,'status'=>1])->first();

        $data['attribute'] = ProductAttribute::
        where('product_id',$data['product']->id)
        ->leftjoin('attributes','attributes.id','=','product_attributes.att_type_id')
        ->select('att_type_id','type')
        ->get();

        $data['category_product'] = Product::where(['category_id'=>$data['product']->category_id,'status'=>1])->get();

        return response()->json(['data' => $data]);

    }

    public function categoryProduct($id){

        $data['product'] = Product::with('attribute')->where(['category_id'=>$id,'status'=>1])->orderBy('id','DESC')->get();

        return view('frontend.category-product',compact('data'));
    }

    public function searchProduct(Request $request){

        $data['product'] = Product::with('attribute')->where('product_title', 'LIKE', '%' . $request->search . '%')->where('status',1)->orderBy('id','DESC')->get();

        return view('frontend.search-product',compact('data'));
    }
}

resources/views/frontend/cart.blade.php
@extends('layouts.frontend.app')
@section('title') হোম @endsection
@section('content')

    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>প্রোডাক্ট</th>
                            <th>টাকা</th>
                            <th>পরিমাণ</th>
                            <th>মোট</th>
                            <th>ডিলিট</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        @if (Session::get('success'))
                        <div class="alert alert-info">
                             {{Session::get('success')}}
                          </div>
                        @endif
                        @if (Session::get('error'))
                        <div class="alert alert-danger">
                             {{Session::get('error')}}
                          </div>
                        @endif
                      @foreach($data as $item)
                            <tr>
                                <td class="align-middle"><img src="{{asset('dashboard/product/'.$item->products->product_image)}}" alt="" style="width: 50px;"> {{$item->products->product_title}} {{$item->type}}</td>
                                <td class="align-middle">{{englishToBanglaNumber($item->products->product_price)}}</td>
                                <form class="mb-30" action="{{route('cart.update',$item->id)}}" method="post">
                                    @csrf
                                    {{method_field('PATCH')}}
                                    <td class="align-middle">
                                        <div class="input-group quantity mx-auto" style="width: 100px;">
                                            <div class="input-group-btn">
                                                <button class="btn btn-sm btn-primary btn-minus" >
                                                <i class="fa fa-minus"></i>
                                                </button>
                                            </div>
                                            <input type="text" name="quantity" class="form-control form-control-sm bg-secondary border-0 text-center" value="{{$item->quantity}}">
                                            <div class="input-group-btn">
                                                <button class="btn btn-sm btn-primary btn-plus">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </td>
                                  </form>
                                <td class="align-middle">{{englishToBanglaNumber(number_format($item->total_price))}}</td>
                                <form class="mb-30" action="{{route('cart.destroy',$item->id)}}" method="post">
                                    @csrf
                                    {{method_field('DELETE')}}
                                  <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                                </form>
                            </tr>

                         @endforeach
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                {{-- <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form> --}}
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">প্রোডাক্ট সারাংশ</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>সাবটোটাল</h6>
                            <h6>{{englishToBanglaNumber(subTotal())}}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">ডেলিভারি চার্জ</h6>
                            <h6 class="font-weight-medium">{{englishToBanglaNumber(deliveryCharge())}}</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>সর্বমোট</h5>
                            <h5>{{englishToBanglaNumber(total())}}</h5>
                        </div>
                        <a href="{{route('checkout_route')}}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">অর্ডার করতে এগিয়ে যান</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->
@endsection

resources/views/frontend/category-product.blade.php
@extends('layouts.frontend.app')
@section('title') হোম @endsection
@section('content')
      <!-- Products Start -->
      <div class="container-fluid pt-5 pb-3">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">প্রোডাক্ট</span></h2>
        <div class="row px-xl-5">
            @foreach($data['product'] as $item)
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <div class="product-item bg-light mb-4">
                    <div class="product-img position-relative overflow-hidden">
                        <img class="img-fluid w-100" src="{{asset('dashboard/product/'.$item->product_image)}}" alt="">
                    </div>
                    <div class="text-center py-4">
                        <a class="h6 text-decoration-none text-truncate" href="{{route('product_details_route',$item->id)}}">{{$item->product_title}}</a>
                        <div class="d-flex align-items-center justify-content-center mt-2">
                            @if ($item->regular_price > 0)
                            <h5>টাকা {{ englishToBanglaNumber($item->regular_price)  }}</h5>
                            <h6 class="text-muted ml-2"><del>টাকা  {{ englishToBanglaNumber($item->product_price) }}</del> </h6>
                        @else
                            <h5>টাকা {{ englishToBanglaNumber($item->product_price)  }}</h5>
                            <h6 class="text-muted ml-2"></h6>
                        @endif
                        </div>
                        <div class="d-flex align-items-center justify-content-center mb-1">
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                        </div>
                        <div class="mb-5">
                            {{-- <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Payment</span></h5> --}}
                            <div class="bg-light">
                                <button class="btn btn-block btn-primary font-weight-bold py-3 open-modal-btn"
                                    data-product-id="{{ $item->id }}">বিস্তারিত দেখুন</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
    <!-- Products End -->

        <!-- Bootstrap Modal -->
        <div class="modal" id="myModal" tabindex="-1" role="dialog" style="width:100%">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">প্রোডাক্ট</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div id="modalContent">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bootstrap Modal -->

        @section('script')
    <!-- Include FontAwesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Your modal button to trigger the modal -->
    <button class="open-modal-btn" data-product-id="1">Open Modal</button>

    <!-- Your modal container -->
    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content" id="modalContent">
                <!-- Modal content will be dynamically added here -->
            </div>
        </div>
    </div>

    <script>

        function changeQuantity(change) {
            const quantityInput = document.getElementById('quantity');
            let quantity = parseInt(quantityInput.value);
            quantity += change;
            if (quantity < 1) {
                quantity = 1;
            }
            quantityInput.value = quantity;
        }

        function addToCart(productid) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            const attributeRadio = document.querySelector('input[name="attribute_id"]:checked');
            const attribute_id = attributeRadio ? attributeRadio.value : null;

            const quantityInput = document.getElementById('quantity');
            const quantity = quantityInput ? parseInt(quantityInput.value) : 1;


            if (!attribute_id) {
                // If no attribute is selected, show an error message
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: 'কার্টে যোগ করার আগে অনুগ্রহ করে একটি নির্বাচন করুন',
                    showConfirmButton: true,
                });
                return; // Return early and do not proceed with adding to cart
            }

            $.ajax({
                type: 'POST',
                url: '{{ route('cart.store') }}',
                data: {
                    product_id: productid,
                    attribute_id: attribute_id,
                    quantity: quantity
                },
                success: function(response) {
                    Swal.fire({
                        icon: 'success',
                        title: response[1],
                        showConfirmButton: false,
                        showCloseButton: true,
                        showCloseButton: true,
                        footer: '<a class="btn btn-primary" href="{{ route('cart.index') }}">আপনার অর্ডার দেখোন</a>',
                        allowOutsideClick: false,
                        timer: 8000
                    });
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }

        // Function to generate attribute radios HTML
        function generateAttributeRadios(attributes) {
            var radiosHtml = '';
            attributes.forEach(function(attribute) {
                radiosHtml += `
                <div class="custom-control custom-radio custom-control-inline">
                    <input type="radio" class="custom-control-input" id="attribute_${attribute.att_type_id}" name="attribute_id" value="${attribute.att_type_id}">
                    <label class="custom-control-label" for="attribute_${attribute.att_type_id}">${attribute.type}</label>
                </div>
            `;
            });
            return radiosHtml;
        }

        // Function to open the modal and fetch data using AJAX
        function openModal(productId) {
            $.ajax({
                type: 'GET',
                url: '/product-details/' + productId,
                dataType: 'json',
                success: function(response) {
                    var product = response.data.product;
                    attributes = response.data.attribute; // Assign the 'attribute' to the global variable
                    var modalContent = `
                    <div class="modal-header">
                        <h5 class="modal-title" id="productModalLabel">${product.product_title}</h5>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-6">
                                <!-- Product Image -->
                                <img src="{{ asset('dashboard/product/') }}/${product.product_image}" alt="${product.product_title}" class="img-fluid mb-3">
                            </div>
                            <div class="col-md-6">
                                <!-- Price and Regular Price -->
                                <p>টাকা: <span id="productPrice">${product.regular_price ? + product.regular_price : product.product_price}  </span></p>
                                <p><del>${product.regular_price ? 'টাকা ' + product.product_price : ''}</del></p>
                                <!-- Product Description -->
                            </div>
                        </div>

                        <!-- Product Attributes -->
                        <div class="form-group mt-3" id="attributeContainer">
                            ${attributes && attributes.length >0 ? '<label>সিলেক্ট করুন</label> <br>' : ''}
                            ${attributes && Array.isArray(attributes) && attributes.length > 0 ? generateAttributeRadios(attributes) : ''}
                        </div>

                        <!-- Quantity input group -->
                        <label>পরিমাণ</label>
                        <div class="input-group quantity" style="width: 130px;">
                            <div class="input-group-btn">
                                <button class="btn btn-primary btn-minus" onclick="changeQuantity(-1)">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                            <input type="text" class="form-control bg-secondary border-0 text-center" name="quantity" id="quantity" value="1">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary btn-plus" onclick="changeQuantity(1)">
                                    <i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        ${product.product_description}
                    </div>

                    <div class="modal-footer">
                        <!-- Close button -->
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">বন্ধ করুন</button>
                        <!-- Add to Cart button -->
                        <button type="button" class="btn btn-primary" onclick="addToCart(${product.id})">কার্টে যোগ করুন</button>
                    </div>
                `;

                    $('#modalContent').html(modalContent);
                    $('#myModal').modal('show');
                },
                error: function(error) {
                    console.error('Error fetching data: ' + JSON.stringify(error));
                }
            });
        }

        // Attach the function to the button click event using a class selector
        $(document).ready(function() {
            $('.open-modal-btn').click(function() {
                var productId = $(this).data('product-id');
                openModal(productId);
            });
        });
    </script>
@endsection
@endsection