routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\frontend\FrontendController;
use App\Http\Controllers\admin\ProductCategoryController;
use App\Http\Controllers\admin\ProductAttributeController;
use App\Http\Controllers\admin\ProductController;
use App\Http\Controllers\admin\OfferController;
use App\Http\Controllers\admin\SliderController;
use App\Http\Controllers\frontend\CartController;
use App\Http\Controllers\frontend\CheckoutController;
use App\Http\Controllers\admin\OrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [FrontendController::class, 'index'])->name('home_route');
Route::get('/shop', [FrontendController::class, 'shop'])->name('shop_route');
Route::get('/product-details/{id}', [FrontendController::class, 'productDetails'])->name('product_details_route');
Route::get('/category-product/{id}', [FrontendController::class, 'categoryProduct'])->name('category_product_route');
Route::get('/search', [FrontendController::class, 'searchProduct'])->name('search_product_route');

Route::resource('cart',CartController::class);
Route::get('checkout',[CheckoutController::class,'index'])->name('checkout_route');
Route::post('place-order',[CheckoutController::class,'placeOrder'])->name('place_order_route');


//admin route
Route::prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth'], function(){
        Route::get('dashboard',[AdminController::class, 'index'])->name('admin.dashboard');
        Route::resource('category',ProductCategoryController::class);
        Route::resource('attribute',ProductAttributeController::class);
        Route::resource('product',ProductController::class);
        Route::resource('offer',OfferController::class);
        Route::resource('slider',SliderController::class);
        Route::resource('order',OrderController::class);
    });
});

app/Models/Attribute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Attribute extends Model
{
    protected $fillable = [
        'type',
        'created_by'
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->created_by = Auth::id();
        });
    }
    use HasFactory;
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use App\Models\ProductCategory;
use App\Models\ProductAttribute;
use App\Models\User;

class Product extends Model
{

    protected $fillable = [
        'category_id',
        'product_code',
        'product_title',
        'product_price',
        'product_image',
        'product_description',
        'created_by',
        'status',
    ];
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->created_by = Auth::id();
        });
    }

    public function category(){
        return $this->belongsTo(ProductCategory::class);
    }

    public function created_user(){
        return $this->belongsTo(User::class,'created_by');
    }

    public function attribute(){
        return $this->hasMany(ProductAttribute::class);
    }


    use HasFactory;
}

app/Http/Controllers/admin/ProductController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\ProductAttribute;
use App\Models\Attribute;
use DataTables;

class ProductController extends Controller
{

      /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
   /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Product::with('category','created_user')->orderBy('id','desc')->get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('status', function($row){
                         if($row->status==1){
                           return 'Active';
                         }else{
                            return 'In active';
                         }
                    })
                    ->addColumn('category', function($row){
                       return $row->category->product_category;
                    })
                    ->addColumn('image', function($row){
                        return '<img src="'.asset('dashboard/product/'.$row->product_image).'" width="30%" height="30%" class="img-fluid">';
                     })
                    ->addColumn('created', function($row){
                        return $row->created_user->name;
                     })
                    ->addColumn('action', function($row){
                        if($row->created_by==auth()->user()->id){
                            return '<a href="' . route('product.edit', $row->id) .'" class="edit btn btn-primary btn-sm">Edit</a>';
                        }
                     })
                    ->rawColumns(['status','category','image','created','action'])
                    ->make(true);
        }
        return view('dashboard.admin.product.index');
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        $category = ProductCategory::where('status',1)->get();
        $att_type = Attribute::select('id','type')->get();
        return view('dashboard.admin.product.create',compact('category','att_type'));
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $request->validate([
            'category_id' => 'required',
            'product_title' => 'required',
            'product_price' => 'required|numeric',
            'product_image' => 'required|image|mimes:jpeg,png,jpg,gif,svg,webp|max:2048',
            'status' => 'required',
        ]);

        // Get the file from the request
        $image = $request->file('product_image');

        // Generate a unique name for the file to avoid conflicts
        $filename = time().'.'.$image->getClientOriginalExtension();

        // Save the image to the public folder
        $image->move('dashboard/product/', $filename);

       $data = Product::create([
            'category_id'=>$request->category_id,
            'product_title'=>$request->product_title,
            'product_price'=>$request->product_price,
            'regular_price'=>$request->regular_price,
            'product_description'=>$request->product_description,
            'product_image'=>$filename,
            'status'=>$request->status,
        ]);

        if(isset($request->attribute)){
           for($i=0;$i<count($request->attribute);$i++){
                $att = new ProductAttribute;
                $att->product_id = $data->id;
                $att->att_type_id = $request->attribute[$i];
                $att->save();
           }
        }

        return redirect()->route('product.index')->with('success','Product has been created successfully.');
    }


    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\CourseCategory  $company
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
        $data['product']    = Product::find($id);
        $data['category']   = ProductCategory::where('status',1)->get();
        $data['att_type']   = Attribute::select('id','type')->get();
        return view('dashboard.admin.product.edit',compact('data'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\company  $company
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request,$id)
    {

        $product=Product::find($id);

        $request->validate([
            'category_id' => 'required',
            'product_title' => 'required',
            'product_price' => 'required|numeric',
            'product_image' => 'image|mimes:jpeg,png,jpg,gif,svg,webp|max:2048',
            'status' => 'required',
        ]);

        if ($request->hasFile('product_image')) {
                  // Get the file from the request
            $image = $request->file('product_image');

            // Generate a unique name for the file to avoid conflicts
            $filename = time().'.'.$image->getClientOriginalExtension();

            // Save the image to the public folder
            $image->move('dashboard/product/', $filename);
        }else{
            $filename = $product->product_image;
        }

        Product::where('id',$id)->update([
            'category_id'=>$request->category_id,
            'product_title'=>$request->product_title,
            'product_price'=>$request->product_price,
            'regular_price'=>$request->regular_price,
            'product_image'=>$filename,
            'product_description'=>$request->product_description,
            'status'=>$request->status,
        ]);

        if(isset($request->attribute)){
            ProductAttribute::where('product_id',$id)->delete();
            for($i=0;$i<count($request->attribute);$i++){
                 $att = new ProductAttribute;
                 $att->product_id = $id;
                 $att->att_type_id = $request->attribute[$i];
                 $att->save();
            }
         }

        return redirect()->route('product.index')->with('success','Product has been updated successfully.');
    }

}

resources/views/dashboard/admin/product/attribute/create.blade.php
@extends('layouts.app')
@section('title') Category @endsection
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Product Attribute</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section class="content">
      <div class="container-fluid">
        <div class="card">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <h4 class="mt-3 mb-3">Create Product Attribute</h4>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form action="{{ route('attribute.store') }}" method="POST">
                        @csrf

                         <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 mt-2">
                                <div class="form-group">
                                    <strong>Attribute:</strong>
                                    <input type="text" name="type" class="form-control" placeholder="Enter type" required>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 mt-3 mb-3">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/dashboard/admin/product/attribute/edit.blade.php
@extends('layouts.app')
@section('title') Teacher @endsection
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Attribute</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section class="content">
      <div class="container-fluid">
        <div class="card">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <h4 class="mt-3 mb-3">Update Attribute</h4>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form action="{{ route('attribute.update',$attribute->id) }}" method="POST">
                        @csrf
                         {{method_field('PATCH')}}
                         <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 mt-2">
                                <div class="form-group">
                                    <strong>Attribute:</strong>
                                    <input type="text" name="type" value="{{$attribute->type}}" class="form-control" placeholder="Course category" required>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 mt-3 mb-3">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/dashboard/admin/product/attribute/index.blade.php
@extends('layouts.app')
@section('title') Category @endsection
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Product Attribute</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <section class="content">
      <div class="container-fluid">
         @if(session()->has('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
         @endif

         <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>Sl</th>
                        <th>Attribute</th>
                        <th width="100px">Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
      </div>
    </section>
  </div>

  @section('script')

  <script>
    $(document).ready(function() {
               $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('attribute.index') }}",
                columns: [
                    {
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex',
                },
                {data: 'type', name: 'type'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });
  </script>
  @endsection
@endsection